amplitude/Amplitude-iOS

Amplitude.xcodeproj/xcshareddata/xcschemes/Amplitude.xcscheme
Amplitude.xcodeproj/xcshareddata/xcschemes/AmplitudeTests.xcscheme
Amplitude/Amplitude.h
Amplitude/Amplitude.m
AmplitudeTests/InitializeTests.m

setUserProperties:replace takes a BOOL for whether to merge into or replace the existing user properties set.
Also added support for CI and new tests for setUserProperties.

Add setUserProperties:replace: for adding user properties incrementally

---

Amplitude/Amplitude.m

Use AMPLITUDE_LOG for debug messages

Change log function

---

Amplitude/AMPDeviceInfo.m
Amplitude/Amplitude.m
AmplitudeTests/Amplitude+Test.h
AmplitudeTests/Amplitude+Test.m
AmplitudeTests/BaseTestCase.h
AmplitudeTests/BaseTestCase.m
AmplitudeTests/DeviceInfoTests.m

6 failed runs out of 100 runs
* 3 from memory issues (double free, modifying freed pointer)
* 2 timed out (test session exited(-1) without completing)
* 1 ApiKey not set (on lots of tests)

Fix flakey tests

---

Amplitude.xcodeproj/project.pbxproj
Amplitude/Amplitude.m
AmplitudeTests/AmplitudeTests.m

* only retry if eventCount multiple of threshold
* added backoff logic for upload retries
* added amplitude test file for testing logEvent logic

Improve upload logic

---

Amplitude/Amplitude.h
Amplitude/Amplitude.m
AmplitudeTests/AmplitudeTests.m
CHANGELOG.md

Similar to: https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/AmplitudeClient.java#L223-L232

add ability to go offline

---

Amplitude.xcodeproj/project.pbxproj
Amplitude/Amplitude.m
AmplitudeTests/AmplitudeTests.m
CHANGELOG.md
README.md

Thanks to @andyyc for the original PR. Additional changes:
* update initializeApiKey to skip logic if already initialized
* added a Readme section for instructions for iOS extensions
* verified integration with a [demo app](https://github.com/amplitude/iOS-Extension-Demo)

Ios extensions

---

Amplitude/AMPDatabaseHelper.m
Amplitude/AMPIdentify.m
Amplitude/AMPRevenue.m
Amplitude/AMPUtils.m
Amplitude/Amplitude.m
CHANGELOG.md
README.md

Log helper

---

Amplitude/Amplitude.m
CHANGELOG.md
README.md

Addresses: https://github.com/amplitude/Amplitude-iOS/issues/93

allow ability to silence error messages

---

README.md

Fix import syntax of Carthage.

Add badges for Carthage and CocoaPods.

---

Amplitude/AMPDeviceInfo.m

Added new iPhone 7 models and some missing old iPhones.

update phone model list for AMPDeviceInfo

---

Amplitude/AMPDeviceInfo.m
CHANGELOG.md

Quick fix for https://github.com/amplitude/Amplitude-iOS/issues/151

fix unknown carrier caching

---

Amplitude/Amplitude.h

Feature request from customer: https://github.com/amplitude/Amplitude-iOS/issues/180
added some notes to the header file to explain caveats

make startOrContinueSession public

---

Amplitude/Amplitude.m

SDK starts background task (Finite Length task) when move to background state. 
After that, SDK tries to upload all accumulated events to the server, and only in success case the sdk ends background task.
i've added ending this background task in all Fail cases. For example, the case when there is no accumulated events to upload(background task requests, but upload do not even to starts). in that case app wastefully uses all processor time given by Operation System. With often expirations of background task OS could decide to provide much less processor time, till the moment that time will not provided at all.
and from docs:
> If you do not end your tasks in a timely manner, the system terminates your app.
https://developer.apple.com/documentation/uikit/core_app/managing_your_app_s_life_cy …

added finishing background tasks on failed cases of uploading events

---

Amplitude.xcodeproj/project.pbxproj
Amplitude.xcodeproj/xcshareddata/xcschemes/Amplitude.xcscheme
Amplitude.xcodeproj/xcshareddata/xcschemes/AmplitudeFramework.xcscheme
Amplitude.xcodeproj/xcshareddata/xcschemes/AmplitudeTVOS.xcscheme
Amplitude.xcodeproj/xcshareddata/xcschemes/AmplitudeTests.xcscheme
AmplitudeTests/AmplitudeTVOSTests.m
AmplitudeTests/AmplitudeTests.m

Updating: https://github.com/amplitude/Amplitude-iOS/pull/139
Tested via tvOS carthage demo app: https://github.com/amplitude/tvOS-Carthage-Demo-App

Carthage tvos support

---

Amplitude.xcodeproj/project.pbxproj
Sources/Amplitude/AMPDeviceInfo.m

Don't use version string for os version in mac

Tweaks before mac support

---

Sources/Amplitude/AMPDeviceInfo.m

I hope this update would be realesed soon, as we can't track iPhone SE 2 on out project

Add iPhone SE 2 model tracking

---

Amplitude.podspec

- #315 didn't have the correct file patterns, this will fix it

chore: update pod source_files

---

.github/workflows/release.yml
AppledocSettings.plist
release.config.js

Fix for removing non-amplitude files from SDK website

docs: remove non amplitude files from sdk website

---

.github/pull_request_template.md
.github/workflows/semantic-pr.yml
README.md
release.config.js

Support for changing primary branch

build: switch primary branch to main

---

Sources/Amplitude/Amplitude.h

docs: fixed typo in Amplitude.h

---

Sources/Amplitude/AMPIdentify.h

- The actual [feat PR](https://github.com/amplitude/Amplitude-iOS/commit/c71382f115e0584828d598b6aedd39919b110aa7) was missing the commit tag so it wasn't picked up by semantic release. This PR will let semantic-release know to do a feat release
- Small doc change to enable commit
- 

feat: Add preInsert, postInsert and remove functions to Identify and Group Identify

---

Sources/Amplitude/AMPTrackingOptions.h
Sources/Amplitude/Amplitude.h

Add docs for `[Amplitude setTrackingOptions]` and `AMPTrackingOptions`

docs: Add docs for [Amplitude setTrackingOptions]

---

Sources/Amplitude/AMPStorage.h
Sources/Amplitude/AMPStorage.m
Sources/Amplitude/Amplitude.m
Sources/Amplitude/Public/Amplitude.h

https://amplitude.atlassian.net/wiki/spaces/sdk/pages/1395720193/iOS+Next+Gen+Disk+Writing+Architecture

perf: Localstorage I/O optimization and batching strategies, streaming to disk

---

Amplitude.xcodeproj/project.pbxproj
Sources/Amplitude/AMPDatabaseHelper.h
Sources/Amplitude/AMPDatabaseHelper.m
Sources/Amplitude/AMPStorage.h
Sources/Amplitude/AMPStorage.m
Sources/Amplitude/Amplitude.m

perf: Add the migration part to local storage performance improvement

---

Amplitude.xcodeproj/project.pbxproj
Amplitude.xcodeproj/xcshareddata/xcschemes/Amplitude_iOSTests.xcscheme
Sources/Amplitude/AMPStorage.m
Tests/AMPStorageTests.m

Add tests for the AMPStorage file, a new file created for the iOS architecture revamp
* [ X ] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-iOS/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?

test: Add new AMPStorage test, also into iOS Tests scheme

---

Sources/Amplitude/AMPStorage.m
Sources/Amplitude/Amplitude.m
Tests/AMPStorageTests.m
Tests/Amplitude+Test.h
Tests/Amplitude+Test.m
Tests/AmplitudeTests.m
Tests/AmplitudeiOSTests.m
Tests/BaseTestCase.m
Tests/SetupTests.m

Fix most of the test cases for the file storage.
Things will be fixed in the following pr:
1. update makeEventUploadPostRequest function signature 
2. add eventId 
3. fix test cases fail because of _updatingCurrently.
4. fix session test.

Local storage test and fix

---

Sources/Amplitude/Amplitude.m
Tests/AmplitudeTests.m

fix: add event_id to event payload and change makeEventUploadPostRequest func signature

---

release.config.js

- Fix release command so we can add new files
- `git commit -am` will only add files changes for tracked files
- Current missing files are added in https://github.com/amplitude/Amplitude-iOS/pull/372

docs: fix command for github pages

---

.github/workflows/jira-issue-create.yml

Update JIRA bot with the right fields

chore: update JIRA bot

---

Sources/Amplitude/Public/Amplitude.h

- Public the setEventUploadMaxBatchSize api
* [ x ] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-iOS/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* [ x ] Does your PR have a breaking change?:

feat: public the setEventUploadMaxBatchSize api

---

Package.swift

Fixes #382 
* Does your PR have a breaking change?:   No

fix: update swift package to support connector package

---

Package.swift

Adds support on Swift Package Manager for WatchOS
Fixes https://github.com/amplitude/Amplitude-iOS/issues/370
* Does your PR have a breaking change? No

feat: add support on Swift Package Manager for WatchOS

---

.github/workflows/release.yml

fix: fix release action

---

.github/workflows/jira-issue-create.yml

chore: use the reusable workflow to create jira issue

---

Sources/Amplitude/AMPIdentifyInterceptor.m
Sources/Amplitude/Amplitude.m
Tests/IdentifyInterceptorTests.m

Fix the issue of https://github.com/amplitude/Amplitude-iOS/issues/462

fix: fix the compatible issue with macOSSonoma

---

.github/workflows/release.yml

Followed the fix [here](https://github.com/amplitude/Amplitude-Swift/commit/8430f1dafd95dba7c102fbceeaf7a74d33b19cf8). 

chore: fix release github action

---

.github/workflows/release.yml

fix: fix for release pipeline

---

Sources/Amplitude/Amplitude.m

Added name for background task started on enterBackground to improve debugging.

refactor: Added name for background task started on enterBackground 

---

README.md

Force updating the version of the SDK

fix: Force push version

---

.github/workflows/release.yml
.github/workflows/test.yml
Cartfile.resolved

see https://github.com/actions/runner-images/issues/10721

chore: update github runner image
