amplitude/Amplitude-iOS

Amplitude/Amplitude.h
Amplitude/Amplitude.m
AmplitudeTests/InitializeTests.m
README.md

This will allow apps to add a UI for allowing user to opt out of tracking. It also allows users to opt back in. During any period opt out is enabled, all logged events (including revenue and sessions) are ignored and not persisted anywhere.

Add logic to disable logging for users that wish to opt out.

---

Amplitude.m

-[NSData base64Encoding] is deprecated from iOS 7.0

Fix base64 string deprecation

---

Amplitude/AMPLocationManagerDelegate.m

Updates AMPLocationManagerDelegate.m to use the correct authorization
constants based on definition of `__IPHONE_8_0` in Availability.h.

Fix CLLocationManager authorization constants warn

---

Amplitude.xcodeproj/project.pbxproj
Amplitude/AMPConstants.m
Amplitude/AMPDeviceInfo.m
Amplitude/Amplitude.h
Amplitude/Amplitude.m
Amplitude/CHANGELOG.md
AmplitudeTests/SessionTests.m
AmplitudeTests/SetupTests.m
CHANGELOG.md
README.md

Start sessions on didBecomeActive instead of willEnterForeground and don't start a session during module initialization. This stops a session from being started when a silent push notif is tracked (the app never becomes active).
In the usual case (user starts app from the icon or from an alerting push notif), the app starts, Amplitude is initialized with an api key, and the session is started when UIApplicationDidBecomeActiveNotification fires as the app UI takes over.
DidBecomeActive fires only slightly more often than WillEnterForeground. It may fire when a phone call is received while the app is open or after the user enters the task switcher or notification overlay. Since startSession doesn't start a new session if one is already active, that shouldn't cause issues. The calls to …

Fix session handling when tracking silent push notifs

---

Amplitude/Amplitude.m

performSelector:withObject:afterDelay is not working.
The performSelector timer is tied to the thread of the operation. Once the performSelector call is made the timer is released and uploadEventsInBackground is never called.
Reference to similar issue with performSelector:withObject:afterDelay
http://stackoverflow.com/questions/16956321/ios-performselectorwithobjectafterdelay-not-working

Fix issue with events not being sent every x seconds.

---

Amplitude/Amplitude.m
AmplitudeTests/SessionTests.m
CHANGELOG.md

Following the logic from the Android SDK: https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/AmplitudeClient.java#L327-L330
Reproduced infinite loop in tests and verified that patch fixes the loop

don't check session when sending session events

---

Amplitude.xcodeproj/project.pbxproj
Amplitude/AMPConstants.h
Amplitude/AMPConstants.m
Amplitude/AMPRevenue.h
Amplitude/AMPRevenue.m
Amplitude/Amplitude.h
Amplitude/Amplitude.m
AmplitudeTests/AmplitudeTests.m
AmplitudeTests/RevenueTests.m
CHANGELOG.md
README.md

Add a new `Revenue` class that wraps revenue properties. The new class adds support for new fields like revenueType, logging event properties with revenue events, etc. Contains a little bit of logic to do some verification (like to make sure all the required fields are present). Converts into an event_properties dictionary which can be passed into logEvent

Revenue v2

---

Amplitude/Amplitude.m

The extra semi-colon may generate a warning on some projects.

Removed extra semi-colon after function implementation.

---

Amplitude/Amplitude.m
CHANGELOG.md

`_eventsDataPath` needs to be available in `upgradePrefs`. This bug crash was introduced in v3.6.0 and affects users who are upgrading straight from v2.1.1 or older.
Fixes: https://github.com/amplitude/Amplitude-iOS/issues/102

fix crash during upgrade prefs init

---

Amplitude/AMPDatabaseHelper.m
AmplitudeTests/AMPDatabaseHelperTests.m
AmplitudeTests/SessionTests.m
CHANGELOG.md

Casting the long long NSNumber to NSInteger caused overflow, since NSInteger size depends on the platform, in the case of iPhone 5C and earlier, it's 32-bit. We should instead be using the long long value

fix 32 bit overflow

---

Amplitude/AMPDatabaseHelper.m
Amplitude/Amplitude.m
AmplitudeTests/AMPDatabaseHelperTests.m
CHANGELOG.md

Sometimes depending on the customer's instrumentation, the event serialization yields a null event. We want to detect when that happens and log an error to notify the customer.
We also need to handle null events when fetching from the database and skip over those events.

handle null event strings

---

Amplitude/Amplitude.m
AmplitudeTests/Amplitude+Test.h
AmplitudeTests/AmplitudeTests.m
CHANGELOG.md

This removes the last objective-c try catch statement from our SDK.
We need to check the iOS version before calling the newer iOS 9 method. Checking NSFoundationVersionNumber is Apple's recommended method for checking.
The nice thing is I can run the unit test on an iOS 8 emulator as well as an iOS 9 emulator. I verified that the unarchiving works in iOS 9, and the unarchiving is skipped in iOS 8. Also if I remove the `(floor(NSFoundationVersionNumber) > NSFoundationVersionNumber_iOS_8_4)` check and run it on iOS 8, I verify that it crashes when trying to call the new method.

switch to unarchiving event dict with new ios 9 method

---

Amplitude-iOS.podspec
Amplitude/SSLCertificatePinning/ISPCertificatePinning.m

Per my correspondence with Varun, Wendy and Dan, we're hoping to enable SSL Pinning in our implementation of Amplitude. The instructions Dan gave us was to:
a. download the source from https://github.com/amplitude/Amplitude-iOS/archive/master.zip
b. install the entire 'Amplitude' subdirectory directly into our project
From my examination of your pod spec, it would appear the only reason ☝️ is necessary is because the pod spec _only_ includes .h / .m files in the top level folder. 
This PR simply modifies the pod spec to include everything in the 'Amplitude' folder, so that (hopefully) we're not forced to choose between integrating Amplitude via Cocoapods or enabling SSL Pinning.

Amplitude SSL Pinning included with Amplitude's Cocoapod

---

Amplitude/Amplitude.m

Since Xcode 9 we now have a [Main Thread Checker](https://developer.apple.com/documentation/code_diagnostics/main_thread_checker) that will warn us when an API thats reserved for the main thread is used on a background thread. Where this falls apart is that if any XCTest triggers this code path the simulator hangs and as a result CI fails. There is some reading [here](http://shashikantjagtap.net/main-thread-checker-xcuitests-xcode-9/) that explores some workarounds.
In the meantime until Apple fixes this we should ensure that Amplitude uses main thread APIs on the main thread always
This closes https://github.com/amplitude/Amplitude-iOS/issues/147

Use UIApplication APIs on the main thread to avoid violations

---

Amplitude/Amplitude.m
AmplitudeTests/SessionTests.m

`[self enterForeground]` sets the `_inForeground` flag, initializes the session information, and uploads unsent events. We manually call this method in `initializeWithApiKey` because when the SDK is initialized, the `enterForeground` notification will already have been triggered by the app.
Issue: this piece of checks application state, which is now forbidden by Apple on background threads. This causes a main queue violation warning in Xcode, and can crash unit tests.
Proposed solution: Rather than calling enterForeground, we just run the pieces of logic that are required. Similar to the Android SDK, we can always just initialize the session information in the init method on the background queue (so just call it directly). We still need to set the foreground flag, and that HAS to be done …

Main thread violation

---

Amplitude/AMPDeviceInfo.h
Amplitude/AMPDeviceInfo.m
Amplitude/Amplitude.h
Amplitude/Amplitude.m
AmplitudeTests/DeviceInfoTests.m

Add a user-configurable flag that skips the IDFA fetching logic.
```objective-c
[[Amplitude instance] disableIdfaTracking];
[[Amplitude instance] initializeApiKey:@"my_api_key"];
```

add flag to disable idfa tracking

---

Amplitude/Amplitude+SSLPinning.h

Amplitude was corrupting our debug console because there was a missing import statement in one of the SSL extensions.
This keeps the extension but makes it a little less error prone.

[Debug] Fix import so it doesn't corrupt debug console

---

Amplitude.xcodeproj/project.pbxproj
Amplitude/AMPDatabaseHelper.h
Amplitude/AMPDatabaseHelper.m
Amplitude/Amplitude.m
AmplitudeTests/Amplitude+Test.h
AmplitudeTests/Amplitude+Test.m
AmplitudeTests/BaseTestCase.m
AmplitudeTests/DatabaseRecoveryTests.m
AmplitudeTests/SessionTests.m

To make iOS SDK more resilient to SQLite exceptions, add a callback method to repersist SDK metadata (device id, user id) back into database after reset.
* Added a void block callback to AMPDatabaseHelper that can be called after resetting the database. Online sources say to hold onto a copy of the block instead of retaining the block directly.
* Next had to change how we were accessing some of the metadata, things like `optOut`, `lastEventTime` were reloaded from database every time and not kept in memory. Changed it so we only need to load them once during initialization into memory
* Once the metadata is in memory, then we can add a callback handler to re-insert them on db fail
iOS counterpart to: https://github.com/amplitude/Amplitude-Android/pull/173

Insert metadata db reset

---

Amplitude/AMPDatabaseHelper.m

We need to close the database connection even if it failed to open
Report: https://github.com/amplitude/Amplitude-iOS/issues/172

close sqlite db even if fail to open

---

Amplitude/Amplitude.m

Making some modifications to ichina's PR: https://github.com/amplitude/Amplitude-iOS/pull/186
Instead of calling `endBackgroundTasksIfNeeded` in every early return in the upload method, just call it one time at the very end of the `onEnterBackground` handler
https://developer.apple.com/library/archive/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html
Tested in demo app, made sure that the `endBackgroundTasksIfNeeded` gets called after flushing or if no events are queued when going into background

Fix end background tasks

---

Amplitude.xcodeproj/project.pbxproj
Amplitude.xcodeproj/xcshareddata/xcschemes/AmplitudeTVOS.xcscheme

Hi there,
when I use Amplitude with Carthage on tvOS:
`carthage bootstrap --no-use-binaries --platform "tvOS"`
I get the following error message:
> Dependency "Amplitude-iOS" has no shared framework schemes for any of the platforms: tvOS
> 
> If you believe this to be an error, please file an issue with the maintainers at Optional("https://github.com/amplitude/Amplitude-iOS/issues/new")
In order to build for tvOS I added another framework target (copy of the iOS one) with some tvOS specific build settings. I added it to the shared AmplitudeTVOS scheme which was already there for testing.
Best,
Fabian

Carthage tvos support

---

Amplitude/Amplitude.m

This reverts commit 282dbb37d17e4aeed41c131c53b510554888ab65.
The background task would end before the final events were sent to amplitude. The `uploadEventsWithLimit` function called before this will end the background task for us.

Revert "replace multiple endTasks with one final endTasks"

---

Amplitude-iOS.podspec
Amplitude/AMPConstants.m
Amplitude/AMPDatabaseHelper.m
Amplitude/AMPRevenue.m
Amplitude/AMPURLConnection.m
Amplitude/AMPURLSession.m
Amplitude/SSLCertificatePinning/ISPCertificatePinning.m
CHANGELOG.md
README.md

Wrapping all NSLogs to allow suppressing it in non-dev environments. This will at least prevent crashes unless debug mode is turned on.
Related issue: https://github.com/amplitude/Amplitude-iOS/issues/204

Wrap the NSLogs so that we can suppress logs when not in debug mode

---

Amplitude/Amplitude.m

This attempts to address https://github.com/amplitude/Amplitude-iOS/issues/206
The fix is inspired by https://github.com/firebase/firebase-ios-sdk/pull/3837/files
For some reason, I can't manually trigger my previous backgroundTask error. Without repro steps, I'm walking in the dark a bit.
cc: @manan19

Only try to end the backgroundTask if the app is in the background

---

CHANGELOG.md

Hi, the new version released today, but seems like the change log release date hasn't been changed yet (Still 19, September). Made a little fix

fix: wrong changelog date, should be October, 8 for version 4.8.2

---

Sources/Amplitude/Amplitude.m

- Use rangeOfComposedCharacterSequencesForRange to avoid bad truncation
Test:
- Repro it with a lot emojis
- Verified the fix and saw no exceptions thrown

Fix partial truncation for string with unicode (e.g. emoji)

---

Package.swift

When adding Amplitude as a SwiftPM dependency to my project, it worked fine in Xcode 11.3 but started to fail in 11.4 BETA due to it not finding the sources. This fix works with both versions of Xcode.

Fix Swift package manager support

---

Amplitude.podspec
Amplitude.xcodeproj/project.pbxproj

`Amplitude-iOS.podspec` will be deprecated. 
Added `Amplitude.podspec`.

Remove macOS from `Amplitude-iOS.podspec`

---

Amplitude.xcodeproj/project.pbxproj
Sources/Amplitude/AMPDeviceInfo.h
Sources/Amplitude/AMPDeviceInfo.m
Sources/Amplitude/Amplitude.h
Sources/Amplitude/Amplitude.m
Tests/AmplitudeTests.m
Tests/BaseTestCase.m
Tests/DeviceInfoTests.m

- Made IDFA entirely external to the amplitude-ios library.
- Updated tests.
- Added documentation around the new adSupportBlock.

iOS 14 IDFA rework

---

Package.swift

Excludes AppledocSettings.plist from the target and explicitly adds files in Resources as resources for SPM.
Closes #292

Add files as resources or exclude if not used

---

Sources/Amplitude/Amplitude.m

Hopefully this meets your style guidelines; it's been a while since I coded Objective-C.

fix: Abort execution of completion block after dynamic config refresh completes if self is now nil (#288)

---

.github/workflows/release.yml

Changes `semantic-release` auto-updates repo bot from `@semantic-release-bot` to `amplitude-sdk-bot`

ci: change semantic-release bot

---

Podfile
Podfile.lock

This PR removes the `source` from the Podfile, so the new (well, not so new anymore :) cocoapods cdn is used as source instead of the old, quite massive Specs repository. I felt the need for this change because I wanted to contribute another bugfix and in order to do this, I had to run `pod install`, which took forever because cocoapods first had to clone the Specs repo. Doing this switch should remove some friction for other people who want to contribute.

build(cocoapods): Remove source from Podfile, run pod install

---

Sources/Amplitude/Amplitude.h
Sources/Amplitude/Amplitude.m
Sources/Amplitude/AmplitudePrivate.h

- Move property declaration to `Amplitude.m` to fix usage in Swift
- Deprecate and document `setUserId(userId)` for `setUserId(userId, startNewSession)`
- Fixes #282 

fix: Swift UserId and DeviceId setter

---

Sources/Amplitude/Amplitude.h

This PR adds DEPRECATED_MSG_ATTRIBUTE() calls to methods in Amplitude.h that were previously marked as deprecated by a **Note** in their docstring.
* Does your PR have a breaking change?:   no

fix(deprecations): Use DEPRECATED_MSG_ATTRIBUTE instead of notes

---

Sources/Amplitude/AMPEventExplorer.m
Sources/Amplitude/AMPUtils.h
Sources/Amplitude/AMPUtils.m
Sources/Amplitude/Amplitude.m

This PR 
- fixes deprecation warnings for iOS 12.0 and 13.0, tvOS 11.0 
- adds a `diagnostic ignored` around the usage of the function `CC_MD5`, which was deprecated in iOS 13.0 but [is only used for the checksum field](https://github.com/amplitude/Amplitude-iOS/issues/250#issuecomment-655224554), thus it should be fine to silence the warning
* Does your PR have a breaking change?:   no

fix(deprecation warnings): Fix deprecation warnings

---

.github/workflows/release.yml
release.config.js

- Fixes release process to correctly generate appledocs and push to `gh-pages` branch
- Tested on fork

ci: appledoc release fix

---

.github/workflows/release.yml
.github/workflows/test.yml

- Use `pod lib lint` instead of `pod spec lint`
- `pod lib lint` validates local code, while `pod spec lint` validates remote code associated with current tag
- Example: The release of `v7.1.1` had a false positive validation because `pod spec lint` was validating `v7.1.0` instead
- Add podfile validation to `test.yml`
- Current CI check will fail because of warnings that will be fixed in future PR

ci: Podfile validation

---

Sources/Amplitude/AMPDatabaseHelper.m
Sources/Amplitude/AMPEventExplorer.m
Sources/Amplitude/Amplitude.m

This PR unifies the declarations of blocks without input parameters and without return value.
They are now all declared like this `^{` instead of `^(){` or `^(void){`. This is consistent with
the majority of declarations for blocks like this in the codebase.
* Does your PR have a breaking change?:   no

style(blocks): Remove `()` and `(void)` before block declarations

---

Sources/Amplitude/Amplitude.m

- #301 introduced 3 compiler warnings when running `pod lib lint`
- 2 fixed by adding macOS 10.13 to `@available` check 
- 1 fixed by adding `-Wunguarded-availability` directive

fix: macOS 10.11/10.13 compile warning fix

---

Sources/Amplitude/AMPConfigManager.h
Sources/Amplitude/AMPConfigManager.m
Sources/Amplitude/AMPDatabaseHelper.h
Sources/Amplitude/AMPDatabaseHelper.m
Sources/Amplitude/AMPDeviceInfo.h
Sources/Amplitude/AMPDeviceInfo.m
Sources/Amplitude/AMPEventExplorer.m
Sources/Amplitude/AMPIdentify.h
Sources/Amplitude/AMPIdentify.m
Sources/Amplitude/AMPRevenue.h
Sources/Amplitude/AMPRevenue.m
Sources/Amplitude/AMPTrackingOptions.h
Sources/Amplitude/AMPTrackingOptions.m
Sources/Amplitude/AMPUtils.h
Sources/Amplitude/AMPUtils.m
Sources/Amplitude/Amplitude.h
Sources/Amplitude/Amplitude.m
Sources/Amplitude/ISPCertificatePinning.h
Sources/Amplitude/ISPCertificatePinning.m
Sources/Amplitude/ISPPinnedNSURLConnectionDelegate.m

This PR unifies the use of whitespaces
- in interface and category declarations
```
@interface Foo : NSObject
@interface Foo ()
@interface Foo (CategoryName)
```
- in implementation declarations:
```
// Without ivars
@implementation Foo
// With ivars
@implementation Foo {
Bar *_bar;
}
```
- in method declarations
```
- (Foo *)createFooFromBar:(Bar *)bar andBaz:(Baz *)baz;
- (Foo)createFooFromBar:(Bar)bar andBar:(Baz)baz;
```
- in method calls
```
[Foo doSomethingWithBar:bar andBaz:baz];
```
- in type casts
```
... = (Foo *)bar;
... = (Bar)baz;
```
- in variable declarations
```
Foo *foo = ...
```
Apart from that, it fixes
- two instances where there were two whitespaces between the `)` and the `{` of a conditional
- one instance where a whitespace was missing between the `)` and the `{` …

style(whitespaces): Improve whitespace consistency

---

Sources/Amplitude/Amplitude.h
Tests/SessionTests.m

- Add `setSessionId` to header
- Add tests for setting session id
- Closes #294 

feat: Add setSessionId to public API

---

Sources/Amplitude/AMPConstants.h
Sources/Amplitude/AMPConstants.m
Sources/Amplitude/Amplitude.h
Sources/Amplitude/Amplitude.m

- Make default `application/x-www-form-urlencoded` value a constant
- delet

feat: Set content-type header for HTTP requests

---

Amplitude.podspec

Adds ` s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }` to the podspec file.
* [X ] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-iOS/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?: No

feat(podspec): Add defines modules to podspec for React Native support

---

Amplitude.podspec

I broke the Cocoapods integration in: https://github.com/amplitude/Amplitude-iOS/pull/335. Oops. Here I edited the podspec file to fix it.
`pod lib lint` should now pass:

fix: Changed the new resources path in podspec file to fix Cocoapods

---

.github/workflows/release.yml
.github/workflows/semantic-pr.yml
.github/workflows/test.yml

Fixes Github actions warning `The macOS virtual environment has been updated to Catalina (v10.15). Please update your workflow and change the line 'runs-on: macOS-10.14' to 'runs-on: macOS-latest'`

ci: update mac OS 10.15

---

Amplitude.xcodeproj/xcshareddata/xcschemes/Amplitude_watchOS.xcscheme
Framework/AmplitudeFramework.h

Hey folks, this PR builds on #330 by adding a new shared scheme to the project for building the watchOS framework with Carthage. It also adds the newly created `AMPBackgroundNotifier` to the umbrella header when targeting watchOS.

fix: Add watchOS scheme for building with Carthage

---

Amplitude.xcodeproj/project.pbxproj
Framework/AmplitudeFramework.h
Sources/Amplitude/AMPMiddleware.m
Sources/Amplitude/AMPMiddlewareRunner.h
Sources/Amplitude/AMPMiddlewareRunner.m
Sources/Amplitude/Amplitude.m
Sources/Amplitude/Public/AMPMiddleware.h
Sources/Amplitude/Public/Amplitude.h
Tests/AmplitudeTests.m
Tests/MiddlewareRunnerTests.m

- add middleware support
- add unit tests

feat: add middleware support

---

Sources/Amplitude/Amplitude.m
Sources/Amplitude/Public/Amplitude.h

Rename method setEventUploadMaxBatchSize to enable support in Swift

fix: fix method for swift

---

Sources/Amplitude/AMPDeviceInfo.m

Mac with M1 CPU can run ios app, the hw.machine will return iPad platform tag. In the getPlatformString method, added a boolean value isiOSAppOnMac, if it's true and target os is not osx, use hw.model instead of hw.machine.
* [X ] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-iOS/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:  <no>

fix: show correct device info for ios app runs on M1 mac

---

Sources/Amplitude/AMPConstants.h
Sources/Amplitude/AMPConstants.m
Sources/Amplitude/AMPPlan.m
Sources/Amplitude/Public/AMPPlan.h
Tests/AmplitudeTests.m
Tests/PlanTests.m

Add versionId to tracking plan data

feat: Add versionId to tracking plan data

---

Sources/Amplitude/AMPDeviceInfo.m
Tests/DeviceInfoTests.m

This PR addresses the wrong carrier information issue reported in https://github.com/amplitude/Amplitude-iOS/issues/399:
- introduce the condition for checking `iOS 12` and use the corresponding method for retrieving carrier info
- tested in an iPhone 13 mini device (one sim only)
- choose to get the updated carrier information always instead of monitoring the notification event
Yes
* Does your PR have a breaking change?:  
No

fix: wrong carrier info with deprecated method

---

Package.swift

This reverts commit 55ee555c68c4c8e36d1166b608447cab3aec6b4f.
This PR is to revert the https://github.com/amplitude/Amplitude-iOS/pull/398, for the recent issue: https://github.com/amplitude/Amplitude-iOS/issues/401.

revert: "Compile with code coverage enabled (#398)"

---

Sources/Amplitude/Amplitude.m

- fix: turn requiringSecureCoding on, adjust the available version
Noticed that we already switch to the recommended methods:
- `NSKeyedArchiver archiveRootObject` => `NSKeyedArchiver archivedDataWithRootObject`
- https://developer.apple.com/documentation/foundation/nskeyedarchiver/1410621-archiverootobject?language=objc
- https://developer.apple.com/documentation/foundation/nskeyedarchiver/2962880-archiveddatawithrootobject 
- `NSKeyedUnarchiver unarchiveTopLevelObjectWithData` => `NSKeyedUnarchiver unarchivedObjectOfClass`
- https://developer.apple.com/documentation/foundation/nskeyedunarchiver/1574811-unarchivetoplevelobjectwithdata
- https://developer.apple.com/documentation/foundation/nskeyedunarchiver/2962884-unarchivedobjectofclass
Enable the `requiringSecureCoding` as …

fix: turn requiringSecureCoding on, adjust the available version

---

Amplitude.xcodeproj/project.pbxproj
Sources/Amplitude/Amplitude.m
Sources/Amplitude/Public/Amplitude.h
Tests/AmplitudeTests.m

Customers need to call clearAll followed with set identify calls.
But SDK logic is `ignore all identify call after the clearAll operations`
Provided this as a workaround to let the customer do:
```
NSMutableDictionary *userProperties = [NSMutableDictionary dictionary];
[userProperties setValue:@"-" forKey:@"$clearAll"];
NSMutableDictionary *setOpProperties = [NSMutableDictionary dictionary];
[setOpProperties setValue:@"value1" forKey:@"prop1"];
[userProperties setObject:setOpProperties forKey:@"$set"];
[[Amplitude instance] logEvent:@"$identify" withEventProperties:nil withUserProperties: userProperties ];
```
For more reference:
https://amplitude.atlassian.net/browse/DXOC-44

feat: expose more logEvent function signature

---

Amplitude.xcodeproj/project.pbxproj
Framework/AmplitudeFramework.h
Sources/Amplitude/AMPConstants.h
Sources/Amplitude/AMPConstants.m
Sources/Amplitude/AMPIngestionMetadata.m
Sources/Amplitude/Amplitude.m
Sources/Amplitude/Public/AMPIngestionMetadata.h
Sources/Amplitude/Public/Amplitude.h
Tests/AmplitudeTests.m
Tests/IngestionMetadataTests.m

- feat: add ingestion_metadata field
Add this option in the configuration, which can be used in the library wrapper/code generation/dynamic loading cases, for setting the `ingestion_metadata` information.

feat: add ingestion_metadata field

---

Sources/Amplitude/Amplitude.m
Sources/Amplitude/Public/Amplitude.h
Tests/AmplitudeTests.m

This pr is related to this[ jira ticket](https://amplitude.atlassian.net/jira/software/c/projects/AMP/boards/197?modal=detail&selectedIssue=AMP-59346&assignee=60185777b4982300703075c9).
Originally, the initialization function will block the main thread caused by the `checkInForeground` callback function.
This pr is for providing a workaround to allow customers manually call the checkInForeground on OnEnterForeGround. 
* [ x ] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-iOS/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?: No

feat: add workaround to manually check in foreground

---

Sources/Amplitude/Amplitude.m
Sources/Amplitude/Public/Amplitude.h
Tests/AmplitudeTests.m

The content is the same as this [pr](https://github.com/amplitude/Amplitude-iOS/pull/412). The original PR doesn't have the right commit message so it won't trigger the semantic release. This PR has the right commit message.

feat: add possibility to manually check in foreground

---

Sources/Amplitude/Amplitude.m
Tests/AmplitudeTVOSTests.m
Tests/AmplitudeTests.m
Tests/AmplitudeiOSTests.m

- fix: response handler when 200 and various errors

fix: response handler when 200 and various errors

---

Sources/Amplitude/AMPEventUtils.h
Sources/Amplitude/AMPEventUtils.m
Sources/Amplitude/AMPIdentifyInterceptor.m
Tests/AmplitudeTests.m

* Update Identify intercept logic to transfer intercepted events on user identity change (user id, device id)

fix: AMP-69475 transfer intercepted Identify's on user identity change

---

Sources/Amplitude/AMPIdentifyInterceptor.m

Version didn't bump on last release for some reason. 
This PR has `fix: ` in both the PR title and the commit message. Hoping this should bump to `8.15.1`

fix: transfer intercepted Identify's on user identity change

---

Sources/Amplitude/AMPDeviceInfo.m

This is the fix for https://amplitude.atlassian.net/browse/DXOC-526?focusedCommentId=169089
TARGET_OS_MACCATALYST is the iPad app that runs on MacOS. Based on the previous logic, the os version will be the iOS version. It makes sense to use the mac version for the os version for this case. Otherwise, the os will be `macos 15.0` which is not a valid macOS version.  Check here for how the current os version looks like https://analytics.amplitude.com/linearity/chart/6db6un2/edit/us3pssm.
With these changes, the TARGET_OS_MACCATALYST will fall into checking the mac os version instead.

fix: fix os version

---

.github/workflows/semantic-pr.yml
Sources/Amplitude/AMPIdentifyInterceptor.m
Sources/Amplitude/AMPUtils.h
Sources/Amplitude/AMPUtils.m
Tests/IdentifyInterceptorTests.m

* https://amplitude.atlassian.net/browse/DXOC-747
* updated identify merging logic to ignore nil values to prevent clearing existing user properties
* Does your PR have a breaking change?: No

fix: updated identify merging logic to ignore nil values

---

Sources/Amplitude/AMPIdentifyInterceptor.m
Tests/Amplitude+Test.h
Tests/Amplitude+Test.m
Tests/AmplitudeTests.m
Tests/IdentifyInterceptorTests.m
Tests/SessionTests.m

Update identify collapsing logic to send actions on separate identify event.
Added small delays to session tests to make them stable in CI.

fix: update identify collapsing logic to send actions on separate identify event

---

.github/workflows/release.yml
.github/workflows/test.yml

Try to fix CI tests - cache key didn't include XCode version and the cache was restored for previous XCode version. Something like:
```
Cache restored from key: macOS-ruby-2.7.x-gems-553f4ac067309ad8e96575e2d4ca9118b6741a35581c85d274c6a1e785458fa7-pods-b0491051b34f7da0cb4b36524405c751b8411c6cdb1c5930ee2f02329afbd096
```
Warning in logs:
```
The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```
I tried to add XCode version to cache keys - cache should be updated but it doesn't help (first run - okm second run - the same error).
Now I remove caching at all.

chore: try to fix CI build - remove caching

---

.github/workflows/release.yml

* Fix [error deleting `appledocs` folder](https://github.com/amplitude/Amplitude-iOS/actions/runs/5126540057/jobs/9221162366) after install

fix: appledoc in CI release workflow

---

Sources/Amplitude/AMPDeviceInfo.m

Replace `malloc` -> `calloc` to fix CWE-789 vulnerability

fix: malloc -> calloc to fix CWE-789 vulnerability

---

Sources/Amplitude/Amplitude.m

* Remove MD5 usage to prevent security warnings

fix: remove MD5 usage

---

.github/workflows/test.yml

Fix outdated test setups.
My recent PR failed on test: https://github.com/amplitude/Amplitude-iOS/actions/runs/7659377311/job/20874360703?pr=473
Comment out flaky tvOS tests as what we did for macOS tests. They are not stable. See this [PR](https://github.com/Mercy811/Amplitude-iOS/pull/5) which triggers tvOS tests twice, one passed but one failed. 

ci: fix test.yml

---

Amplitude.xcodeproj/project.pbxproj
Sources/Amplitude/AMPDatabaseHelper.m
Sources/Amplitude/AMPUtils.h
Sources/Amplitude/AMPUtils.m
Tests/AMPUtilsTests.m

- fix for app directory in macos when sandbox is not enabled for app.
When sandboxed, sample path:
/Users/{user}/Library/Containers/com.test.Test/Data/Library/com.amplitude.database
When not sandboxed, sample path:
/Users/{user}/Library/com.amplitude.database.com.test.Test
* Does your PR have a breaking change?:  Only affecting the special case for apps on macos without sandbox enabled.

fix: fix for when macos sandbox disabled

---

Sources/PrivacyInfo.xcprivacy

Add privacy manifest file. It pretty much the same as https://github.com/amplitude/Amplitude-Swift/pull/109
- Fields are the same
- Domains are different as next-gen SDKs are using HTTP V2 

feat: add privacy manifest for iOS 17

---

README.md

* update README to note deprecation and promote migration to Swift SDK

chore: update README to note deprecation and promote migration to Swift SDK

---

Sources/Amplitude/Amplitude.m

Copy extra properties to make sure it does not get deallocated before the middlewares run

fix: Copy extra params to prevent deallocation

---

Amplitude.podspec
Package.swift

This PR adds exporting of the PrivacyInfo information added in version 8.18.0 for use via SPM and Cocoapods.
I have tested it with SPM and Cocoapods sample projects, and now it successfully fetches the information.
The process to add it in Cocoapods is the same as used by multiple projects. Ref. https://github.com/CocoaPods/CocoaPods/issues/10325#issuecomment-1718723762 and to add it in SPM, I have looked at other projects such as Revenuecat https://github.com/RevenueCat/purchases-ios/blob/main/Package.swift.
Issues Related:
https://github.com/amplitude/Amplitude-iOS/issues/482
https://github.com/amplitude/Amplitude-iOS/issues/470
Thanks for Amplitude!
> ### Checklist

fix(PrivacyInfo) SPM/Cocoapods support for privacy manifest

---

Sources/PrivacyInfo.xcprivacy

- Update "Product interaction" to "Linked to User"
- Delete tracking domains 
> If you set NSPrivacyTracking to true then you need to provide at least one internet domain in NSPrivacyTrackingDomains; otherwise, you can provide zero or more domains.
This PR is from https://github.com/amplitude/amplitude-dev-center/pull/276#discussion_r1550220212.

chore: delete tracking domain from privacy manifest

---

Sources/Amplitude/Amplitude.m
Sources/Amplitude/Public/Amplitude.h
Tests/AmplitudeTests.m
Tests/SetupTests.m

feat: add method to get device ID synchronously

---

.github/workflows/test.yml
Sources/Amplitude/Amplitude.m
Tests/AmplitudeTests.m

fix: assign deviceId correctly on new device

---

Amplitude.podspec

Fix for https://github.com/amplitude/Amplitude-iOS/pull/487#issuecomment-2043709593
Adopt `resource_bundle` syntax to prevent name resource name conflicts when statically linked in cocoapods (see https://guides.cocoapods.org/syntax/podspec.html#resource_bundles).
I've tested that the certificates are bundled correctly and a privacy report generates properly when linked statically and when linked as a framework (via `use_frameworks!` flag in the Podfile).

fix: specify resource_bundle vs resource for resources in cocoapods

---

Sources/Amplitude/Amplitude.m
Tests/AmplitudeTests.m

UIApplicationWillEnterForegroundNotification fires both at initial launch and when returning from the background. Because we were using a different notification (UIApplicationDidFinishLaunchingNotification) to detect if the app open was from the background, we were effectively were firing the event twice. Instead, rely on UIApplicationState to determine if we were opened from the background.

Fix: Don't report two app open events at initial launch

---

Sources/Amplitude/AMPDatabaseHelper.m

We've seen some reported crashes in sqlite internals coming from our SDK. I suspect this is a threading issue as most of the crashes occur on background threads and the customer is using multiple instances of Amplitude.
Our current threading strategy is to dispatch all db operations to a single queue, and to recreate a connection per operation. This _should_ work with the default multithread [threading strategy](https://www.sqlite.org/threadsafe.html), where sqlite is thread safe if connections aren't shared between threads.
But, dispatching to a single queue doesn't mean that we always run on the same thread, and we have no synchronization mechanism between instances of the SDK. This means that a single thread may run connections to two different databases, though none should …

fix: Prevent crashes in multithreaded environments with sqlite.

---

Sources/Amplitude/Amplitude.m

I've been able to reproduce the crash mentioned in https://github.com/amplitude/Amplitude-iOS/issues/498 with the following initialization:
```
let amp = Amplitude.instance(withName: "foo")
amp.initializeApiKey("...")
amp.logEvent("test")
DispatchQueue.global().async {
while true {
amp.setTrackingOptions(AMPTrackingOptions().disableLatLng())
}
}    
```
It seems this is caused by concurrent access to tracking options, so I've marked the related variables as atomic.

fix: mark trackingoptions as atomic to prevent issues from concurrent access

---

Sources/Amplitude/AMPMiddleware.m
Sources/Amplitude/AMPMiddlewareRunner.h
Sources/Amplitude/AMPMiddlewareRunner.m
Sources/Amplitude/Amplitude.m
Sources/Amplitude/Public/AMPMiddleware.h
Sources/Amplitude/Public/Amplitude.h
Tests/Amplitude+Test.h
Tests/AmplitudeTests.m
Tests/MiddlewareRunnerTests.m

Adds methods to middleware to improve support for the upcoming session replay plugin

feat: extend middleware for session replay

---

Sources/Amplitude/AMPMiddleware.m
Sources/Amplitude/AMPMiddlewareRunner.h
Sources/Amplitude/AMPMiddlewareRunner.m
Sources/Amplitude/Amplitude.m
Sources/Amplitude/Public/AMPMiddleware.h
Sources/Amplitude/Public/Amplitude.h
Tests/AmplitudeTests.m

Adds ability to remove middleware, and subscribe to changes to userId, sessionId, deviceId, and optOut settings.

feat: Add more functionality to middleware

---

Sources/Amplitude/AMPMiddleware.m
Sources/Amplitude/AMPMiddlewareRunner.h
Sources/Amplitude/AMPMiddlewareRunner.m
Sources/Amplitude/Amplitude.m
Sources/Amplitude/Public/AMPMiddleware.h
Tests/AmplitudeTests.m

Adds a callback to middleware when it is removed from the amplitude instance

feat: add middleware removed callback

---

Sources/Amplitude/Public/AMPDefaultTrackingOptions.h

sessions tracking is actually defaulted to disabled. (see https://github.com/amplitude/Amplitude-iOS/issues/510)

fix: correct documentation for sessions default value

---

Sources/Amplitude/Public/AMPServerZone.h

Both AmplitudeCore and Amplitude-iOS contain the same ObjC enum, `AMPServerZone`.  This causes build errors when Session Replay and our legacy SDK are both imported within the same project.  Note that enums can simultaneously exist in both projects if both the ObjC definitions are exactly the same.
A few possible fixes:
1/ Make Amplitude-iOS import AmplitudeCore and import the enums from there. This is suboptimal as Amplitude-iOS is deprecated and we don't want to add a new dependency.
2/ Match enum cases from Amplitude-iOS to AmplitudeCore by adding EU and US. Then, we'd have the issue of unprefixed enum cases for ObjC in our supported SDKs.
3/ Match enum cases from AmplitudeCore to Amplitude-iOS, alias existing US/EU constants for backwards compatibility. This may be slightly breaking, …

fix: prefix server zone constants
